/**
 * Re-exports for Constants/ConfigSocialMedia
 * Auto-generated by migrateFrontend.cjs
 */

export * from '@/Constants/ConfigSocialMedia/socialPlatforms';
export * from '@/Constants/ConfigSocialMedia/socialPlatformsConfig';
