<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
  /**
   * Run the migrations.
   */
  public function up(): void
  {
    Schema::table('publications', function (Blueprint $table) {
      // Drop the check constraint if it exists (common in Laravel PG enum impl)
      // Then alter to string.
      // Since we don't know the exact name of the constraint generated by Laravel,
      // we will try to just set it to string, but if that fails we might need raw SQL.
      // However, the error "syntax error at or near check" suggests Laravel is TRYING to add a check constraint.
      // Let's just define it as a string without 'change()' if possible, or use raw SQL to drop constraint.

      // Simplest fix: Just change to string. If 'change()' is causing the 'check' syntax error,
      // it means Laravel is trying to recreate the enum constraint.
      // providing a string type should avoid generating a CHECK (...) IN (...) clause.

      $table->string('status')->change();
    });
  }




  /**
   * Reverse the migrations.
   */
  public function down(): void
  {
    Schema::table('publications', function (Blueprint $table) {
      // $table->enum('status', ['draft', 'published'])->change();
      // Reverting to enum might cause the same issue. Let's just ensure it's a string.
      $table->string('status')->change();
    });
  }
};
