export const PLAN_FEATURES = {
  demo: [
    'fullAccessDays',
    'publications100',
    'socialAccounts20',
    'storage50',
    'aiRequests500',
    'advancedAnalytics',
    'advancedScheduling',
    'calendarSync',
    'bulkOperations',
    'emailSupport',
  ],
  free: [
    'publications3',
    'socialAccounts2',
    'storage1',
    'aiRequests10',
    'basicAnalytics',
    'emailSupport',
  ],
  starter: [
    'publications50',
    'socialAccounts10',
    'storage10',
    'aiRequests100',
    'basicAnalytics',
    'advancedScheduling',
    'calendarSync',
    'emailSupport',
  ],
  professional: [
    'publications200',
    'socialAccounts50',
    'storage100',
    'aiRequestsUnlimited',
    'advancedAnalytics',
    'advancedScheduling',
    'calendarSync',
    'bulkOperations',
    'customBranding',
    'prioritySupport',
  ],
  enterprise: [
    'publicationsUnlimited',
    'socialAccountsUnlimited',
    'storage1TB',
    'aiRequestsUnlimited',
    'advancedAnalytics',
    'whiteLabel',
    'apiAccess',
    'customIntegrations',
    'slaGuarantee',
    'dedicatedSupport',
  ],
} as const;

export type PlanId = keyof typeof PLAN_FEATURES;
