/**
 * Re-exports for types/common
 * Auto-generated by migrateFrontend.cjs
 */

export * from '@/types/common/errors';
export * from '@/types/common/layout';
export * from '@/types/common/optimistic';
export * from '@/types/common/PageProps';
export * from '@/types/common/validation';
